#!/usr/bin/env python3
"""
Golden-vector tests for the Port 20 version-report decoder.

Vectors are generated by the REAL firmware encoder
(stratosonde/firmware Core/Src/version_report.c VersionReport_Build), compiled
and run with the firmware host suite parameters
(tests/host/test_version_report.c):

  VersionReport_Build(f, HEARTBEAT_FORMAT_VERSION=2, VERSION_STAGE_COMMISSIONING, 1234)
    -> 56 01 00 00 02 01 D2 04 00 00 93 27
  VersionReport_Build(f, HEARTBEAT_FORMAT_VERSION=2, VERSION_STAGE_FLIGHT, 0xA5A5)
    -> 56 01 00 00 02 02 A5 A5 00 00 B5 50

(SONDE_FW_MAJOR/MINOR/PATCH = 1.0.0 at the time of writing.)

These guard against silent drift on the next wire bump; if the firmware changes
the frame, this test must be updated in lockstep with a fresh vector.

Run:  python3 test_decode_port20.py
"""

import base64
import unittest

from ground_station import decode_port20_version


def b64(hex_str):
    return base64.b64encode(bytes.fromhex(hex_str.replace(" ", ""))).decode("ascii")


class TestPort20VersionReport(unittest.TestCase):

    GOLDEN_COMMISSIONING = "56 01 00 00 02 01 D2 04 00 00 93 27"
    GOLDEN_FLIGHT = "56 01 00 00 02 02 A5 A5 00 00 B5 50"

    def test_commissioning_golden(self):
        r = decode_port20_version(b64(self.GOLDEN_COMMISSIONING))
        self.assertIsNotNone(r)
        self.assertEqual(r["magic"], 0x56)
        self.assertEqual(r["firmware_version"], "1.0.0")
        self.assertEqual(r["fw_major"], 1)
        self.assertEqual(r["fw_minor"], 0)
        self.assertEqual(r["fw_patch"], 0)
        self.assertEqual(r["format_version"], 2)
        self.assertEqual(r["stage"], 0x01)
        self.assertEqual(r["stage_name"], "COMMISSIONING")
        self.assertEqual(r["mission_minutes"], 1234)
        self.assertTrue(r["crc_valid"])

    def test_flight_golden(self):
        r = decode_port20_version(b64(self.GOLDEN_FLIGHT))
        self.assertIsNotNone(r)
        self.assertEqual(r["format_version"], 2)
        self.assertEqual(r["stage"], 0x02)
        self.assertEqual(r["stage_name"], "FLIGHT")
        self.assertEqual(r["mission_minutes"], 0xA5A5)
        self.assertTrue(r["crc_valid"])

    def test_bad_crc_flagged_not_rejected(self):
        # Flip the last CRC byte: frame still decodes but crc_valid must be False
        bad = "56 01 00 00 02 01 D2 04 00 00 93 28"
        r = decode_port20_version(b64(bad))
        self.assertIsNotNone(r)
        self.assertFalse(r["crc_valid"])

    def test_wrong_magic_rejected(self):
        # First byte not 0x56 -> not a version frame
        self.assertIsNone(decode_port20_version(b64("00 01 00 00 02 01 D2 04 00 00 93 27")))

    def test_wrong_length_rejected(self):
        self.assertIsNone(decode_port20_version(b64("56 01 00 00 02 01 D2 04 00 00 93")))       # 11
        self.assertIsNone(decode_port20_version(b64("56 01 00 00 02 01 D2 04 00 00 93 27 00")))  # 13

    def test_invalid_base64_returns_none(self):
        self.assertIsNone(decode_port20_version("!!!not-base64!!!"))

    def test_unknown_stage_labelled(self):
        # stage byte 0x00 (neither commissioning nor flight); CRC recomputed
        payload = bytes([0x56, 1, 0, 0, 2, 0x00, 0, 0, 0, 0])
        crc = 0xFFFF
        for b in payload:
            crc ^= (b << 8)
            for _ in range(8):
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF if (crc & 0x8000) else (crc << 1) & 0xFFFF
        frame = payload + bytes([crc & 0xFF, (crc >> 8) & 0xFF])
        r = decode_port20_version(base64.b64encode(frame).decode())
        self.assertTrue(r["crc_valid"])
        self.assertTrue(r["stage_name"].startswith("UNKNOWN"))


if __name__ == "__main__":
    unittest.main(verbosity=2)
